config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	get  "projects/test" => "projects#test"
	root "projects#index"

	namespace :admin do
		root "application#index"
		resources :projects, only: [:new, :create, :destroy ]
	end

	resources :projects, only: [:index, :show, :edit, :update] do
		resources :tickets
	end

	
		

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name, presence: true
	has_many :tickets, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  #we have run : rails g devise user ; rails g devise:views 
  belongs_to :author , class_name: "User"
  # afterwords rails  g migration add_author_to_tickets author:refereces
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  #skip_after_action :verify_authorized, :verify_policy_scoped
  before_action :authorize_admin!

  def index
  end

  private

  def authorize_admin!
    authenticate_user!

    unless current_user.admin?
      redirect_to root_path, alert: "You must be an admin"
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

	def test
		render "test"
	end

	#GET /projects/new
	def new
		@project=Project.new
	end

	#POST /projects
	def create
		@project=Project.new(project_params)
		if @project.save
			flash[:notice]="Project has been created"
			#Submit data and post request was done.
			#Create a new browser request, 
			#change url for /projects/new to /projects/:id
			#show a single record information
			redirect_to @project
		else
			flash.now[:alert]="Project has not been created"
			#render the current url /projects/new ; i.e. : new.html.erb ; /projects/
			render action: :new
		end
	end
	
	#DELETE /products/1
	def destroy
		set_project
		@project.destroy
		flash[:notice]="Project has been deleted"
		redirect_to projects_path
	end

	private
	
	#used in create
	def project_params
		params.require(:project).permit(:name, :description)
	end

	#used in destroy
	def set_project
		@project=Project.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:alert]="The project you where looking for could not be found"
		redirect_to projects_path
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

before_action :set_project, only: [:show, :edit, :update]

#new,create,destroy moved to admin/projects_controller.rb

def test
	render "test"
end

#GET /projects/1
def show
end

#GET /projects
def index
	@projects=Project.all
end

#GET /projects/1/edit
def edit 
end

#PATCH/PUT /projects/1
def update
	if @project.update(project_params)
		flash[:notice]="Project has been updated"
		redirect_to @project
	else
		flash[:alert]="Project has not been updated"
		render action: :edit
	end
end

end

private
def project_params
	params.require(:project).permit(:name, :description)
end

#used before in show,edit,update
def set_project
	@project=Project.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:alert]="The project you where looking for could not be found"
		redirect_to projects_path
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	before_action :set_project
	before_action :set_ticket, only: [:show, :edit, :update, :destroy]

	def set_project
		#cfr. @project=Project.find(params[:id])
		@project=Project.find(params[:project_id])
	end
	
	#used before in show,edit,update,destroy
	def set_ticket
		@ticket=@project.tickets.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:alert]="The Ticket you where looking for could not be found"
		redirect_to project_tickets_path
	end

	def ticket_params
		params.require(:ticket).permit(:name, :description)
	end
	
	def new
		#cfr.	@project=Project.new
		#build set the foreign key project_id for the association
		#i.e. project:references in "rails g model ticket ... project:references"
		@ticket=@project.tickets.build
	end

	def create
		#cfr. @project=Project.new(project_params)
		@ticket=@project.tickets.build(ticket_params)
		#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
		@ticket.author=current_user
		if @ticket.save
			flash[:notice]="Ticket has been created"
			#Submit data and post request was done.
			#Create a new browser request, 
			#change url for /projects/new to /projects/:id
			#show a single record information
			#cfr. redirect_to @project
			redirect_to [@project, @ticket]
		else
			flash.now[:alert]="Ticket has not been created"
			# render the current url /projects/new ; i.e. : new.html.erb ; /projects/
			render action: :new
		end
	end

	def show
	end
	
	def edit
	end
	
	def update
		if @ticket.update(ticket_params)
			flash[:notice]="Ticket has been updated"
			redirect_to [@project,@ticket]
		else
			flash.now[:alert]="Ticket has not been updated"
			render "edit"
		end
	end
	
	def destroy
		@ticket.destroy
		flash[:notice]="Ticket has been deleted"
		redirect_to @project
	end

	private :set_project, :ticket_params, :set_ticket
	
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/application/index.html.erb
<h1>Admin::Application#index</h1>
<p>Find me in app/views/admin/application/index.html.erb</p>
<div class="row" id="admin">
  <div class="col-md-9">
    <header>
      <h1>
				Admin Lounge
			</h1>
    </header>
    <p>
			Welcome to Ticketee's Admin Lounge. Please enjoy your stay.
    </p>
  </div>
  <div class="col-md-3">
    <h2>Admin Links</h2>
    <ul class="nav nav-stacked">
			<li>
				Links will go here
			</li>
    </ul>
  </div>
</div>

app/views/admin/projects/_neworedit.html.erb
<%= simple_form_for([:admin,aproject]) do |f|  %>
	<%=render "neworediterrors",bproject: aproject%>
		<%=f.input :name %> 
		<%=f.input :description %> 
		<%=f.submit :submit,class: "btn-primary" %>
<%end%>

app/views/admin/projects/_neworediterrors.html.erb
neworediterrors.html.erb <br>

<% if bproject.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%=pluralize(bproject.errors.count,"error")%>
			prohibited this project from being saved
		</h2>
		
		<ul>
			<% bproject.errors.full_messages.each do |msg| %>
				<li>
					<%=msg %>
				</li>
				<%end %>
		</ul>
	</div>
<%end %>

app/views/admin/projects/new.html.erb
<% @title="Project new" %>

<div class="myheader">
	<h1>New Project</h1>
</div>

<%=render "neworedit",aproject: @project %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
	<%# responsive styling for mobile devices%>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
		<%= @title || "Projectmaster" %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  <%# mitigate csrf cross-site request forgery%>
</head>

<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">

			<div class="navbar-header">
				<%= link_to "Projectmaster", root_path, class: "navbar-brand" %>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
			</div>

			<div class="collapse navbar-collapse" id="collapse">
				<ul class="nav navbar-nav">
					<li class="<%= "active" if current_page?("/") %>">
						<%= link_to "Home", root_path %>
					</li>
					<% unless user_signed_in? %>
						<li class="<%= "active" if current_page?("/users/sign_up") %>">
							<%= link_to "Sign up", new_user_registration_path %>
						</li>
						<li class="<%= "active" if current_page?("/users/sign_in") %>">
							<%= link_to "Sign in", new_user_session_path %>
						</li>
					<% end %>
				</ul>
				<% if user_signed_in? %>
					<div class="navbar-right">
						<p class="navbar-text">
							Signed in as <%= current_user.email %>
						</p>
						<ul class="nav navbar-nav">
							<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %>
							</li>
						</ul>
					</div>
				<% end %>
			</div>
		</div>
	</nav>

	<%# Use bootstrap container (shift more to right) %>
	<div class="container">
		<%# render flash messagges %>
		<% flash.each do |key,message | %>
			<div class="alert alert-<%= key %>">
				<%= message %>
				<%= key %>
			</div>
		<% end %>	
		<%= yield %>
	</div>

</body>
</html>

app/views/projects/_neworedit.html.erb
<%= simple_form_for(aproject) do |f|  %>
	<%=render "neworediterrors",bproject: aproject%>
		<%=f.input :name %> 
		<%=f.input :description %> 
		<%=f.submit :submit,class: "btn-primary" %>
<%end%>

app/views/projects/_neworediterrors.html.erb
neworediterrors.html.erb <br>

<% if bproject.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%=pluralize(bproject.errors.count,"error")%>
			prohibited this project from being saved
		</h2>
		
		<ul>
			<% bproject.errors.full_messages.each do |msg| %>
				<li>
					<%=msg %>
				</li>
				<%end %>
		</ul>
	</div>
<%end %>

app/views/projects/_test.html.erb
TEST2

app/views/projects/edit.html.erb
<% @title="Project edit" %>

<div class="myheader"
	<h1>Edit Project</h1>
</div>

<%=render "neworedit",aproject: @project%>

app/views/projects/index.html.erb
<% @title="Project index" %>

<div class="myheader">
	<h1>Index Project</h1>
	<ul class="actions">
		<li>
			<%# Note:semantic styling, see application.css.scss%>
			<%# Note:fa=font awesome%>
			<%#= link_to "New Project",new_project_path,class: "btn btn-success" %>
			<%= link_to "New Project",new_admin_project_path,class: "new" %>
		</li>
	</ul>
</div>

<div id="projects">
	<% @projects.each do |project| %>
		<h3>
			<%# show %>
			<%=link_to project.name,project %>
		</h3>
		<p>
			<%=project.description%>
		</p>
	<%end %>
</div>

app/views/projects/show.html.erb
<% @title="Project show" %>

<div class="myheader">
	<h1>
		Show project<br>
	</h1>
</div>
<div class="myheader">
	<h1>
		<%= @project.name%>
	</h1>
	<h3>
		<%= @project.description%>
	</h3>
	
	<ul class="actions">
		<li>
			<%=link_to "Edit Project",edit_project_path(@project),class: "edit" %>
		</li>
		<li>
			<%=link_to "Delete Project",admin_project_path(@project),:method=>:delete,:data=>{:confirm=>"Are you sure to delete this project?"},class: "delete" %>
		</li>
		<li>
			<%= link_to "New Ticket",new_project_ticket_path(@project),class: "new" %>
		</li>
		<li>
			<%= link_to "Home",root_path,class: "link" %>
		</li>
	</ul>
</div>

<%# show a single record%>

<ul id="tickets">
	<% @project.tickets.each do |ticket| %>
		<li>
			#
			<%= link_to ticket.name,[@project,ticket] %>
		</li>
	<% end %>	
</ul>

app/views/projects/test.html.erb
test.html.erb <br>
<h1>
TEST1
<%= render :partial=>"test" %>
TEST3
</h1>

app/views/tickets/_neworedit.html.erb
<%= simple_form_for([aproject,aticket]) do |f|  %>
	<%#=render "neworediterrors",bproject: aproject%>
		<%=f.input :name %> 
		<%=f.input :description %> 
		<%=f.submit :submit,class: "btn-primary" %>
<%end%>

app/views/tickets/edit.html.erb
<% @title="Ticket edit" %>

<div class="myheader"
	<h1>Edit Ticket </h1>
</div>

<%=render "neworedit",aproject: @project,aticket: @ticket %>

app/views/tickets/new.html.erb
<% @title="Ticket new" %>

<div class="myheader"
	<h1>New Ticket </h1>
</div>

<%=render "neworedit",aproject: @project,aticket: @ticket %>

app/views/tickets/show.html.erb
<% @title="Ticket show" %>

<div id="ticket">
	<div class="myheader">
		<h1>
			Show Ticket<br>
			<%= @project.name%>
		</h1>
	</div>	

	<div class="myheader">
		<h2>
			<%= @ticket.name%>
		</h2>
		
		<table id="attributes">
			<tr>
				<th>
					Author:
				</th>					
				<td>
					<%= @ticket.author.email%>
				</td>
			</tr>
			<tr>
				<th>
					Created:
				</th>
				<td>
					<%= time_ago_in_words(@ticket.created_at)%>
				</td>
			</tr>
		</table>
		
		
		<ul class="actions">
			<li>
				<%=link_to "Edit Ticket",[:edit,@project,@ticket],class:"edit"%>
			</li>
			<li>
				<%=link_to "Delete Ticket",
										[@project,@ticket],
										method: :delete,
										data: {confirm: "Are you sure you want to delete this ticket?"},
										class:"delete"%>
			</li>
			<li>
				<%=link_to "Goto Project",
										@project,
										class:"link"%>
			</li>
		</ul>
	</div>	
	<%# simple_format : convert line breaks in correct html%>
	<%=simple_format(@ticket.description)%>
</div>